plugins {
    id 'org.jetbrains.kotlin.jvm'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation 'org.briarproject:briar-headless'
    implementation 'org.briarproject:bramble-core'
    implementation 'org.briarproject:bramble-java'
    implementation 'org.briarproject:briar-core'
    implementation 'org.briarproject:bramble-api'
    implementation 'org.briarproject:briar-api'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2'

    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2'
    testImplementation "org.jetbrains.kotlin:kotlin-test:2.2.20"
    testImplementation 'io.mockk:mockk:1.14.6'
}
